#include "cef_loader.h"
#include "dynamic_library.h"
#include "logger.h"

#include <memory>

#ifdef PLATFORM_WINDOWS
#include <windows.h>
#endif

namespace CEFLib {
    // CEF function pointer initializations (auto-generated - 176 functions)
    int(*cef_add_cross_origin_whitelist_entry)(const cef_string_t* source_origin, const cef_string_t* target_protocol, const cef_string_t* target_domain, int allow_target_subdomains) = nullptr;
    struct _cef_binary_value_t*(*cef_base64decode)(const cef_string_t* data) = nullptr;
    cef_string_userfree_t(*cef_base64encode)(const void* data, size_t data_size) = nullptr;
    cef_basetime_t(*cef_basetime_now)(void) = nullptr;
    int(*cef_begin_tracing)(const cef_string_t* categories, struct _cef_completion_callback_t* callback) = nullptr;
    cef_binary_value_t*(*cef_binary_value_create)(const void* data, size_t data_size) = nullptr;
    int(*cef_browser_host_create_browser)(const cef_window_info_t* windowInfo, struct _cef_client_t* client, const cef_string_t* url, const struct _cef_browser_settings_t* settings, struct _cef_dictionary_value_t* extra_info, struct _cef_request_context_t* request_context) = nullptr;
    cef_browser_t*(*cef_browser_host_create_browser_sync)(const cef_window_info_t* windowInfo, struct _cef_client_t* client, const cef_string_t* url, const struct _cef_browser_settings_t* settings, struct _cef_dictionary_value_t* extra_info, struct _cef_request_context_t* request_context) = nullptr;
    int(*cef_clear_cross_origin_whitelist)(void) = nullptr;
    int(*cef_clear_scheme_handler_factories)(void) = nullptr;
    cef_command_line_t*(*cef_command_line_create)(void) = nullptr;
    cef_command_line_t*(*cef_command_line_get_global)(void) = nullptr;
    cef_cookie_manager_t*(*cef_cookie_manager_get_global_manager)(struct _cef_completion_callback_t* callback) = nullptr;
    int(*cef_crash_reporting_enabled)(void) = nullptr;
    cef_request_context_t*(*cef_create_context_shared)(cef_request_context_t* other, struct _cef_request_context_handler_t* handler) = nullptr;
    int(*cef_create_directory)(const cef_string_t* full_path) = nullptr;
    int(*cef_create_new_temp_directory)(const cef_string_t* prefix, cef_string_t* new_temp_path) = nullptr;
    int(*cef_create_temp_directory_in_directory)(const cef_string_t* base_dir, const cef_string_t* prefix, cef_string_t* new_dir) = nullptr;
    int(*cef_create_url)(const struct _cef_urlparts_t* parts, cef_string_t* url) = nullptr;
    int(*cef_currently_on)(cef_thread_id_t threadId) = nullptr;
    int(*cef_delete_file)(const cef_string_t* path, int recursive) = nullptr;
    cef_dictionary_value_t*(*cef_dictionary_value_create)(void) = nullptr;
    int(*cef_directory_exists)(const cef_string_t* path) = nullptr;
    void(*cef_do_message_loop_work)(void) = nullptr;
    cef_drag_data_t*(*cef_drag_data_create)(void) = nullptr;
    int(*cef_end_tracing)(const cef_string_t* tracing_file, cef_end_tracing_callback_t* callback) = nullptr;
    int(*cef_execute_process)(const cef_main_args_t* args, cef_app_t* application, void* windows_sandbox_info) = nullptr;
    cef_string_userfree_t(*cef_format_url_for_security_display)(const cef_string_t* origin_url) = nullptr;
    cef_platform_thread_handle_t(*cef_get_current_platform_thread_handle)(void) = nullptr;
    cef_platform_thread_id_t(*cef_get_current_platform_thread_id)(void) = nullptr;
    int(*cef_get_exit_code)(void) = nullptr;
    void(*cef_get_extensions_for_mime_type)(const cef_string_t* mime_type, cef_string_list_t extensions) = nullptr;
    cef_string_userfree_t(*cef_get_mime_type)(const cef_string_t* extension) = nullptr;
    int(*cef_get_min_log_level)(void) = nullptr;
    int(*cef_get_path)(cef_path_key_t key, cef_string_t* path) = nullptr;
    int(*cef_get_temp_directory)(cef_string_t* temp_dir) = nullptr;
    int(*cef_get_vlog_level)(const char* file_start, size_t N) = nullptr;
#ifdef PLATFORM_LINUX
    XDisplay*(*cef_get_xdisplay)(void) = nullptr;
#endif
    cef_image_t*(*cef_image_create)(void) = nullptr;
    int(*cef_initialize)(const cef_main_args_t* args, const struct _cef_settings_t* settings, cef_app_t* application, void* windows_sandbox_info) = nullptr;
    int(*cef_is_cert_status_error)(cef_cert_status_t status) = nullptr;
    int(*cef_is_rtl)(void) = nullptr;
    int(*cef_launch_process)(struct _cef_command_line_t* command_line) = nullptr;
    cef_list_value_t*(*cef_list_value_create)(void) = nullptr;
    void(*cef_load_crlsets_file)(const cef_string_t* path) = nullptr;
    void(*cef_log)(const char* file, int line, int severity, const char* message) = nullptr;
    cef_media_router_t*(*cef_media_router_get_global)(struct _cef_completion_callback_t* callback) = nullptr;
    cef_menu_model_t*(*cef_menu_model_create)(struct _cef_menu_model_delegate_t* delegate) = nullptr;
    int64_t(*cef_now_from_system_trace_time)(void) = nullptr;
    struct _cef_value_t*(*cef_parse_json)(const cef_string_t* json_string, cef_json_parser_options_t options) = nullptr;
    struct _cef_value_t*(*cef_parse_json_buffer)(const void* json, size_t json_size, cef_json_parser_options_t options) = nullptr;
    struct _cef_value_t*(*cef_parse_jsonand_return_error)(const cef_string_t* json_string, cef_json_parser_options_t options, cef_string_t* error_msg_out) = nullptr;
    int(*cef_parse_url)(const cef_string_t* url, struct _cef_urlparts_t* parts) = nullptr;
    cef_post_data_t*(*cef_post_data_create)(void) = nullptr;
    cef_post_data_element_t*(*cef_post_data_element_create)(void) = nullptr;
    int(*cef_post_delayed_task)(cef_thread_id_t threadId, cef_task_t* task, int64_t delay_ms) = nullptr;
    int(*cef_post_task)(cef_thread_id_t threadId, cef_task_t* task) = nullptr;
    cef_preference_manager_t*(*cef_preference_manager_get_global)(void) = nullptr;
    cef_print_settings_t*(*cef_print_settings_create)(void) = nullptr;
    cef_process_message_t*(*cef_process_message_create)(const cef_string_t* name) = nullptr;
    void(*cef_quit_message_loop)(void) = nullptr;
    int(*cef_register_extension)(const cef_string_t* extension_name, const cef_string_t* javascript_code, cef_v8handler_t* handler) = nullptr;
    int(*cef_register_scheme_handler_factory)(const cef_string_t* scheme_name, const cef_string_t* domain_name, cef_scheme_handler_factory_t* factory) = nullptr;
    int(*cef_remove_cross_origin_whitelist_entry)(const cef_string_t* source_origin, const cef_string_t* target_protocol, const cef_string_t* target_domain, int allow_target_subdomains) = nullptr;
    cef_request_context_t*(*cef_request_context_create_context)(const struct _cef_request_context_settings_t* settings, struct _cef_request_context_handler_t* handler) = nullptr;
    cef_request_context_t*(*cef_request_context_get_global_context)(void) = nullptr;
    cef_request_t*(*cef_request_create)(void) = nullptr;
    int(*cef_resolve_url)(const cef_string_t* base_url, const cef_string_t* relative_url, cef_string_t* resolved_url) = nullptr;
    cef_resource_bundle_t*(*cef_resource_bundle_get_global)(void) = nullptr;
    cef_response_t*(*cef_response_create)(void) = nullptr;
    void(*cef_run_message_loop)(void) = nullptr;
    void(*cef_server_create)(const cef_string_t* address, uint16_t port, int backlog, struct _cef_server_handler_t* handler) = nullptr;
    void(*cef_set_crash_key_value)(const cef_string_t* key, const cef_string_t* value) = nullptr;
    void(*cef_set_osmodal_loop)(int osModalLoop) = nullptr;
    cef_shared_process_message_builder_t*(*cef_shared_process_message_builder_create)(const cef_string_t* name, size_t byte_size) = nullptr;
    void(*cef_shutdown)(void) = nullptr;
    cef_stream_reader_t*(*cef_stream_reader_create_for_data)(void* data, size_t size) = nullptr;
    cef_stream_reader_t*(*cef_stream_reader_create_for_file)(const cef_string_t* fileName) = nullptr;
    cef_stream_reader_t*(*cef_stream_reader_create_for_handler)(cef_read_handler_t* handler) = nullptr;
    cef_stream_writer_t*(*cef_stream_writer_create_for_file)(const cef_string_t* fileName) = nullptr;
    cef_stream_writer_t*(*cef_stream_writer_create_for_handler)(cef_write_handler_t* handler) = nullptr;
    int(*cef_string_ascii_to_utf16)(const char* src, size_t src_len, cef_string_utf16_t* output) = nullptr;
    int(*cef_string_ascii_to_wide)(const char* src, size_t src_len, cef_string_wide_t* output) = nullptr;
    cef_string_list_t(*cef_string_list_alloc)(void) = nullptr;
    void(*cef_string_list_append)(cef_string_list_t list, const cef_string_t* value) = nullptr;
    void(*cef_string_list_clear)(cef_string_list_t list) = nullptr;
    cef_string_list_t(*cef_string_list_copy)(cef_string_list_t list) = nullptr;
    void(*cef_string_list_free)(cef_string_list_t list) = nullptr;
    size_t(*cef_string_list_size)(cef_string_list_t list) = nullptr;
    int(*cef_string_list_value)(cef_string_list_t list, size_t index, cef_string_t* value) = nullptr;
    cef_string_map_t(*cef_string_map_alloc)(void) = nullptr;
    int(*cef_string_map_append)(cef_string_map_t map, const cef_string_t* key, const cef_string_t* value) = nullptr;
    void(*cef_string_map_clear)(cef_string_map_t map) = nullptr;
    int(*cef_string_map_find)(cef_string_map_t map, const cef_string_t* key, cef_string_t* value) = nullptr;
    void(*cef_string_map_free)(cef_string_map_t map) = nullptr;
    int(*cef_string_map_key)(cef_string_map_t map, size_t index, cef_string_t* key) = nullptr;
    size_t(*cef_string_map_size)(cef_string_map_t map) = nullptr;
    int(*cef_string_map_value)(cef_string_map_t map, size_t index, cef_string_t* value) = nullptr;
    cef_string_multimap_t(*cef_string_multimap_alloc)(void) = nullptr;
    int(*cef_string_multimap_append)(cef_string_multimap_t map, const cef_string_t* key, const cef_string_t* value) = nullptr;
    void(*cef_string_multimap_clear)(cef_string_multimap_t map) = nullptr;
    int(*cef_string_multimap_enumerate)(cef_string_multimap_t map, const cef_string_t* key, size_t value_index, cef_string_t* value) = nullptr;
    size_t(*cef_string_multimap_find_count)(cef_string_multimap_t map, const cef_string_t* key) = nullptr;
    void(*cef_string_multimap_free)(cef_string_multimap_t map) = nullptr;
    int(*cef_string_multimap_key)(cef_string_multimap_t map, size_t index, cef_string_t* key) = nullptr;
    size_t(*cef_string_multimap_size)(cef_string_multimap_t map) = nullptr;
    int(*cef_string_multimap_value)(cef_string_multimap_t map, size_t index, cef_string_t* value) = nullptr;
    cef_string_userfree_utf16_t(*cef_string_userfree_utf16_alloc)(void) = nullptr;
    void(*cef_string_userfree_utf16_free)(cef_string_userfree_utf16_t str) = nullptr;
    cef_string_userfree_utf8_t(*cef_string_userfree_utf8_alloc)(void) = nullptr;
    void(*cef_string_userfree_utf8_free)(cef_string_userfree_utf8_t str) = nullptr;
    cef_string_userfree_wide_t(*cef_string_userfree_wide_alloc)(void) = nullptr;
    void(*cef_string_userfree_wide_free)(cef_string_userfree_wide_t str) = nullptr;
    void(*cef_string_utf16_clear)(cef_string_utf16_t* str) = nullptr;
    int(*cef_string_utf16_cmp)(const cef_string_utf16_t* str1, const cef_string_utf16_t* str2) = nullptr;
    int(*cef_string_utf16_set)(const char16_t* src, size_t src_len, cef_string_utf16_t* output, int copy) = nullptr;
    int(*cef_string_utf16_to_lower)(const char16_t* src, size_t src_len, cef_string_utf16_t* output) = nullptr;
    int(*cef_string_utf16_to_upper)(const char16_t* src, size_t src_len, cef_string_utf16_t* output) = nullptr;
    int(*cef_string_utf16_to_utf8)(const char16_t* src, size_t src_len, cef_string_utf8_t* output) = nullptr;
    int(*cef_string_utf16_to_wide)(const char16_t* src, size_t src_len, cef_string_wide_t* output) = nullptr;
    void(*cef_string_utf8_clear)(cef_string_utf8_t* str) = nullptr;
    int(*cef_string_utf8_cmp)(const cef_string_utf8_t* str1, const cef_string_utf8_t* str2) = nullptr;
    int(*cef_string_utf8_set)(const char* src, size_t src_len, cef_string_utf8_t* output, int copy) = nullptr;
    int(*cef_string_utf8_to_utf16)(const char* src, size_t src_len, cef_string_utf16_t* output) = nullptr;
    int(*cef_string_utf8_to_wide)(const char* src, size_t src_len, cef_string_wide_t* output) = nullptr;
    void(*cef_string_wide_clear)(cef_string_wide_t* str) = nullptr;
    int(*cef_string_wide_cmp)(const cef_string_wide_t* str1, const cef_string_wide_t* str2) = nullptr;
    int(*cef_string_wide_set)(const wchar_t* src, size_t src_len, cef_string_wide_t* output, int copy) = nullptr;
    int(*cef_string_wide_to_utf16)(const wchar_t* src, size_t src_len, cef_string_utf16_t* output) = nullptr;
    int(*cef_string_wide_to_utf8)(const wchar_t* src, size_t src_len, cef_string_utf8_t* output) = nullptr;
    cef_task_runner_t*(*cef_task_runner_get_for_current_thread)(void) = nullptr;
    cef_task_runner_t*(*cef_task_runner_get_for_thread)(cef_thread_id_t threadId) = nullptr;
    cef_thread_t*(*cef_thread_create)(const cef_string_t* display_name, cef_thread_priority_t priority, cef_message_loop_type_t message_loop_type, int stoppable, cef_com_init_mode_t com_init_mode) = nullptr;
    int(*cef_time_delta)(const cef_time_t* cef_time1, const cef_time_t* cef_time2, long long* delta) = nullptr;
    int(*cef_time_from_basetime)(const cef_basetime_t from, cef_time_t* to) = nullptr;
    int(*cef_time_from_doublet)(double time, cef_time_t* cef_time) = nullptr;
    int(*cef_time_from_timet)(time_t time, cef_time_t* cef_time) = nullptr;
    int(*cef_time_now)(cef_time_t* cef_time) = nullptr;
    int(*cef_time_to_basetime)(const cef_time_t* from, cef_basetime_t* to) = nullptr;
    int(*cef_time_to_doublet)(const cef_time_t* cef_time, double* time) = nullptr;
    int(*cef_time_to_timet)(const cef_time_t* cef_time, time_t* time) = nullptr;
    void(*cef_trace_counter)(const char* category, const char* name, const char* value1_name, uint64_t value1_val, const char* value2_name, uint64_t value2_val) = nullptr;
    void(*cef_trace_counter_id)(const char* category, const char* name, uint64_t id, const char* value1_name, uint64_t value1_val, const char* value2_name, uint64_t value2_val) = nullptr;
    void(*cef_trace_event_async_begin)(const char* category, const char* name, uint64_t id, const char* arg1_name, uint64_t arg1_val, const char* arg2_name, uint64_t arg2_val) = nullptr;
    void(*cef_trace_event_async_end)(const char* category, const char* name, uint64_t id, const char* arg1_name, uint64_t arg1_val, const char* arg2_name, uint64_t arg2_val) = nullptr;
    void(*cef_trace_event_async_step_into)(const char* category, const char* name, uint64_t id, uint64_t step, const char* arg1_name, uint64_t arg1_val) = nullptr;
    void(*cef_trace_event_async_step_past)(const char* category, const char* name, uint64_t id, uint64_t step, const char* arg1_name, uint64_t arg1_val) = nullptr;
    void(*cef_trace_event_begin)(const char* category, const char* name, const char* arg1_name, uint64_t arg1_val, const char* arg2_name, uint64_t arg2_val) = nullptr;
    void(*cef_trace_event_end)(const char* category, const char* name, const char* arg1_name, uint64_t arg1_val, const char* arg2_name, uint64_t arg2_val) = nullptr;
    void(*cef_trace_event_instant)(const char* category, const char* name, const char* arg1_name, uint64_t arg1_val, const char* arg2_name, uint64_t arg2_val) = nullptr;
    cef_string_userfree_t(*cef_uridecode)(const cef_string_t* text, int convert_to_utf8, cef_uri_unescape_rule_t unescape_rule) = nullptr;
    cef_string_userfree_t(*cef_uriencode)(const cef_string_t* text, int use_plus) = nullptr;
    cef_urlrequest_t*(*cef_urlrequest_create)(struct _cef_request_t* request, struct _cef_urlrequest_client_t* client, struct _cef_request_context_t* request_context) = nullptr;
    cef_v8context_t*(*cef_v8context_get_current_context)(void) = nullptr;
    cef_v8context_t*(*cef_v8context_get_entered_context)(void) = nullptr;
    int(*cef_v8context_in_context)(void) = nullptr;
    cef_v8stack_trace_t*(*cef_v8stack_trace_get_current)(int frame_limit) = nullptr;
    cef_v8value_t*(*cef_v8value_create_array)(int length) = nullptr;
    cef_v8value_t*(*cef_v8value_create_array_buffer)(void* buffer, size_t length, cef_v8array_buffer_release_callback_t* release_callback) = nullptr;
    cef_v8value_t*(*cef_v8value_create_bool)(int value) = nullptr;
    cef_v8value_t*(*cef_v8value_create_date)(cef_basetime_t date) = nullptr;
    cef_v8value_t*(*cef_v8value_create_double)(double value) = nullptr;
    cef_v8value_t*(*cef_v8value_create_function)(const cef_string_t* name, cef_v8handler_t* handler) = nullptr;
    cef_v8value_t*(*cef_v8value_create_int)(int32_t value) = nullptr;
    cef_v8value_t*(*cef_v8value_create_null)(void) = nullptr;
    cef_v8value_t*(*cef_v8value_create_object)(cef_v8accessor_t* accessor, cef_v8interceptor_t* interceptor) = nullptr;
    cef_v8value_t*(*cef_v8value_create_promise)(void) = nullptr;
    cef_v8value_t*(*cef_v8value_create_string)(const cef_string_t* value) = nullptr;
    cef_v8value_t*(*cef_v8value_create_uint)(uint32_t value) = nullptr;
    cef_v8value_t*(*cef_v8value_create_undefined)(void) = nullptr;
    cef_value_t*(*cef_value_create)(void) = nullptr;
    cef_waitable_event_t*(*cef_waitable_event_create)(int automatic_reset, int initially_signaled) = nullptr;
    cef_string_userfree_t(*cef_write_json)(struct _cef_value_t* node, cef_json_writer_options_t options) = nullptr;
    cef_xml_reader_t*(*cef_xml_reader_create)(struct _cef_stream_reader_t* stream, cef_xml_encoding_type_t encodingType, const cef_string_t* URI) = nullptr;
    int(*cef_zip_directory)(const cef_string_t* src_dir, const cef_string_t* dest_file, int include_hidden_files) = nullptr;
    cef_zip_reader_t*(*cef_zip_reader_create)(struct _cef_stream_reader_t* stream) = nullptr;
}

bool loadCEFLibrary(const std::string& libPath) {
    static std::unique_ptr<DynamicLibrary> cef_lib;

#ifdef PLATFORM_WINDOWS
    SetDllDirectoryA(libPath.c_str());
    cef_lib = std::make_unique<DynamicLibrary>(libPath + "\\libcef.dll");
#else
    cef_lib = std::make_unique<DynamicLibrary>(libPath + "/libcef.so");
#endif

    if (!cef_lib->load()) {
        return false;
    }

// Load CEF functions (failure = warning only, not critical)
#define LOAD_FUNC(name) \
    CEFLib::name = cef_lib->getFunction<decltype(CEFLib::name)>(#name); \
    if (!CEFLib::name) { Logger::warn("CEF function not available: " #name); }

    LOAD_FUNC(cef_add_cross_origin_whitelist_entry);
    LOAD_FUNC(cef_base64decode);
    LOAD_FUNC(cef_base64encode);
    LOAD_FUNC(cef_basetime_now);
    LOAD_FUNC(cef_begin_tracing);
    LOAD_FUNC(cef_binary_value_create);
    LOAD_FUNC(cef_browser_host_create_browser);
    LOAD_FUNC(cef_browser_host_create_browser_sync);
    LOAD_FUNC(cef_clear_cross_origin_whitelist);
    LOAD_FUNC(cef_clear_scheme_handler_factories);
    LOAD_FUNC(cef_command_line_create);
    LOAD_FUNC(cef_command_line_get_global);
    LOAD_FUNC(cef_cookie_manager_get_global_manager);
    LOAD_FUNC(cef_crash_reporting_enabled);
    LOAD_FUNC(cef_create_context_shared);
    LOAD_FUNC(cef_create_directory);
    LOAD_FUNC(cef_create_new_temp_directory);
    LOAD_FUNC(cef_create_temp_directory_in_directory);
    LOAD_FUNC(cef_create_url);
    LOAD_FUNC(cef_currently_on);
    LOAD_FUNC(cef_delete_file);
    LOAD_FUNC(cef_dictionary_value_create);
    LOAD_FUNC(cef_directory_exists);
    LOAD_FUNC(cef_do_message_loop_work);
    LOAD_FUNC(cef_drag_data_create);
    LOAD_FUNC(cef_end_tracing);
    LOAD_FUNC(cef_execute_process);
    LOAD_FUNC(cef_format_url_for_security_display);
    LOAD_FUNC(cef_get_current_platform_thread_handle);
    LOAD_FUNC(cef_get_current_platform_thread_id);
    LOAD_FUNC(cef_get_exit_code);
    LOAD_FUNC(cef_get_extensions_for_mime_type);
    LOAD_FUNC(cef_get_mime_type);
    LOAD_FUNC(cef_get_min_log_level);
    LOAD_FUNC(cef_get_path);
    LOAD_FUNC(cef_get_temp_directory);
    LOAD_FUNC(cef_get_vlog_level);
#ifdef PLATFORM_LINUX
    LOAD_FUNC(cef_get_xdisplay);
#endif
    LOAD_FUNC(cef_image_create);
    LOAD_FUNC(cef_initialize);
    LOAD_FUNC(cef_is_cert_status_error);
    LOAD_FUNC(cef_is_rtl);
    LOAD_FUNC(cef_launch_process);
    LOAD_FUNC(cef_list_value_create);
    LOAD_FUNC(cef_load_crlsets_file);
    LOAD_FUNC(cef_log);
    LOAD_FUNC(cef_media_router_get_global);
    LOAD_FUNC(cef_menu_model_create);
    LOAD_FUNC(cef_now_from_system_trace_time);
    LOAD_FUNC(cef_parse_json);
    LOAD_FUNC(cef_parse_json_buffer);
    LOAD_FUNC(cef_parse_jsonand_return_error);
    LOAD_FUNC(cef_parse_url);
    LOAD_FUNC(cef_post_data_create);
    LOAD_FUNC(cef_post_data_element_create);
    LOAD_FUNC(cef_post_delayed_task);
    LOAD_FUNC(cef_post_task);
    LOAD_FUNC(cef_preference_manager_get_global);
    LOAD_FUNC(cef_print_settings_create);
    LOAD_FUNC(cef_process_message_create);
    LOAD_FUNC(cef_quit_message_loop);
    LOAD_FUNC(cef_register_extension);
    LOAD_FUNC(cef_register_scheme_handler_factory);
    LOAD_FUNC(cef_remove_cross_origin_whitelist_entry);
    LOAD_FUNC(cef_request_context_create_context);
    LOAD_FUNC(cef_request_context_get_global_context);
    LOAD_FUNC(cef_request_create);
    LOAD_FUNC(cef_resolve_url);
    LOAD_FUNC(cef_resource_bundle_get_global);
    LOAD_FUNC(cef_response_create);
    LOAD_FUNC(cef_run_message_loop);
    LOAD_FUNC(cef_server_create);
    LOAD_FUNC(cef_set_crash_key_value);
    LOAD_FUNC(cef_set_osmodal_loop);
    LOAD_FUNC(cef_shared_process_message_builder_create);
    LOAD_FUNC(cef_shutdown);
    LOAD_FUNC(cef_stream_reader_create_for_data);
    LOAD_FUNC(cef_stream_reader_create_for_file);
    LOAD_FUNC(cef_stream_reader_create_for_handler);
    LOAD_FUNC(cef_stream_writer_create_for_file);
    LOAD_FUNC(cef_stream_writer_create_for_handler);
    LOAD_FUNC(cef_string_ascii_to_utf16);
    LOAD_FUNC(cef_string_ascii_to_wide);
    LOAD_FUNC(cef_string_list_alloc);
    LOAD_FUNC(cef_string_list_append);
    LOAD_FUNC(cef_string_list_clear);
    LOAD_FUNC(cef_string_list_copy);
    LOAD_FUNC(cef_string_list_free);
    LOAD_FUNC(cef_string_list_size);
    LOAD_FUNC(cef_string_list_value);
    LOAD_FUNC(cef_string_map_alloc);
    LOAD_FUNC(cef_string_map_append);
    LOAD_FUNC(cef_string_map_clear);
    LOAD_FUNC(cef_string_map_find);
    LOAD_FUNC(cef_string_map_free);
    LOAD_FUNC(cef_string_map_key);
    LOAD_FUNC(cef_string_map_size);
    LOAD_FUNC(cef_string_map_value);
    LOAD_FUNC(cef_string_multimap_alloc);
    LOAD_FUNC(cef_string_multimap_append);
    LOAD_FUNC(cef_string_multimap_clear);
    LOAD_FUNC(cef_string_multimap_enumerate);
    LOAD_FUNC(cef_string_multimap_find_count);
    LOAD_FUNC(cef_string_multimap_free);
    LOAD_FUNC(cef_string_multimap_key);
    LOAD_FUNC(cef_string_multimap_size);
    LOAD_FUNC(cef_string_multimap_value);
    LOAD_FUNC(cef_string_userfree_utf16_alloc);
    LOAD_FUNC(cef_string_userfree_utf16_free);
    LOAD_FUNC(cef_string_userfree_utf8_alloc);
    LOAD_FUNC(cef_string_userfree_utf8_free);
    LOAD_FUNC(cef_string_userfree_wide_alloc);
    LOAD_FUNC(cef_string_userfree_wide_free);
    LOAD_FUNC(cef_string_utf16_clear);
    LOAD_FUNC(cef_string_utf16_cmp);
    LOAD_FUNC(cef_string_utf16_set);
    LOAD_FUNC(cef_string_utf16_to_lower);
    LOAD_FUNC(cef_string_utf16_to_upper);
    LOAD_FUNC(cef_string_utf16_to_utf8);
    LOAD_FUNC(cef_string_utf16_to_wide);
    LOAD_FUNC(cef_string_utf8_clear);
    LOAD_FUNC(cef_string_utf8_cmp);
    LOAD_FUNC(cef_string_utf8_set);
    LOAD_FUNC(cef_string_utf8_to_utf16);
    LOAD_FUNC(cef_string_utf8_to_wide);
    LOAD_FUNC(cef_string_wide_clear);
    LOAD_FUNC(cef_string_wide_cmp);
    LOAD_FUNC(cef_string_wide_set);
    LOAD_FUNC(cef_string_wide_to_utf16);
    LOAD_FUNC(cef_string_wide_to_utf8);
    LOAD_FUNC(cef_task_runner_get_for_current_thread);
    LOAD_FUNC(cef_task_runner_get_for_thread);
    LOAD_FUNC(cef_thread_create);
    LOAD_FUNC(cef_time_delta);
    LOAD_FUNC(cef_time_from_basetime);
    LOAD_FUNC(cef_time_from_doublet);
    LOAD_FUNC(cef_time_from_timet);
    LOAD_FUNC(cef_time_now);
    LOAD_FUNC(cef_time_to_basetime);
    LOAD_FUNC(cef_time_to_doublet);
    LOAD_FUNC(cef_time_to_timet);
    LOAD_FUNC(cef_trace_counter);
    LOAD_FUNC(cef_trace_counter_id);
    LOAD_FUNC(cef_trace_event_async_begin);
    LOAD_FUNC(cef_trace_event_async_end);
    LOAD_FUNC(cef_trace_event_async_step_into);
    LOAD_FUNC(cef_trace_event_async_step_past);
    LOAD_FUNC(cef_trace_event_begin);
    LOAD_FUNC(cef_trace_event_end);
    LOAD_FUNC(cef_trace_event_instant);
    LOAD_FUNC(cef_uridecode);
    LOAD_FUNC(cef_uriencode);
    LOAD_FUNC(cef_urlrequest_create);
    LOAD_FUNC(cef_v8context_get_current_context);
    LOAD_FUNC(cef_v8context_get_entered_context);
    LOAD_FUNC(cef_v8context_in_context);
    LOAD_FUNC(cef_v8stack_trace_get_current);
    LOAD_FUNC(cef_v8value_create_array);
    LOAD_FUNC(cef_v8value_create_array_buffer);
    LOAD_FUNC(cef_v8value_create_bool);
    LOAD_FUNC(cef_v8value_create_date);
    LOAD_FUNC(cef_v8value_create_double);
    LOAD_FUNC(cef_v8value_create_function);
    LOAD_FUNC(cef_v8value_create_int);
    LOAD_FUNC(cef_v8value_create_null);
    LOAD_FUNC(cef_v8value_create_object);
    LOAD_FUNC(cef_v8value_create_promise);
    LOAD_FUNC(cef_v8value_create_string);
    LOAD_FUNC(cef_v8value_create_uint);
    LOAD_FUNC(cef_v8value_create_undefined);
    LOAD_FUNC(cef_value_create);
    LOAD_FUNC(cef_waitable_event_create);
    LOAD_FUNC(cef_write_json);
    LOAD_FUNC(cef_xml_reader_create);
    LOAD_FUNC(cef_zip_directory);
    LOAD_FUNC(cef_zip_reader_create);

#undef LOAD_FUNC

    Logger::info("CEF library loaded successfully (176 functions)");
    return true;
}
